improves error handling for argument mismatch
dart-lang/intl_translation pull request #133
Opened 2021-02-12 19:41 UTC by pulsar256

- fixes NPE when Intl definition did contain no arguments while ARB did provide some
- skip the code generation for a message if argument mismatch has been detected instead of aborting the process / code generation.

2021-02-12 19:48 UTC, pulsar256 commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fdart-lang%2Fintl_translation%2Fpull%2F133) for more info**.

@googlebot I signed it!

2022-12-13 09:36 UTC, mosuem requested changes
LGTM after resolving merge conflicts.

2022-12-13 15:19 UTC, pulsar256 commented
I don't know how relevant this PR might be today (after close to two years). Also the commit e6642485a5bb8d1fe5ddbb3cd8f3999bfaa6683c did not only migrate the project to dart null-safety but also did refactor a lot of architecture making a rebase impossible. 

Any strong opinions on this other than closing the PR?

2022-12-13 15:20 UTC, mosuem commented
I am also fine with closing it, as it does not address a high-priority issue. But thanks for contributing, and sorry for the long wait!

2022-12-13 15:20 UTC, closed without merging